### ISSUE TITLE
Add metadata tags for entries in databases.

### ISSUE THREAD

**Issue by JakubCzarlinski** [WarwickAI/wai-platform-v2#60]
Discussed offline.

Adding tags to the visual cards that link to another page was a neat solution in the previous society website that gave extra data about projects and courses.

**Comment by Edward-Upton** [comment]
My initial thoughts for this are to add tags as a default field for all pages, since in many situations we may want to use them.

The tags field will simply be an array of tag UUIDs so that on loading the page we can fetch the information from the DB (like text and colour). 

What kind of information would we like stored with each tag, I'm thinking:

- UUID
- Name (text that will be displayed)
- Type of tag (e.g. `difficulty`, `term`), this will help with filtering later on...
- Colour

**Comment by ojaffe** [comment]
That sounds good ^

Type of tag is ideal, would be nice to have:
- Length of event (day, week)
- Difficulty
- Term
- ...

**Comment by ojaffe** [comment]
Also sorting+filtering for database entries. Not only by tag, but also by other fields (e.g. name of course).

**Comment by Edward-Upton** [comment]
Best to open another issue for filtering

**Comment by Edward-Upton** [comment]
Added in 4aeafccd1960e8382c4348d852951c8546a33e58 and e80542f45bff10a8c29ca0dd3b1c4eb1ebef6e8b

**Comment by JakubCzarlinski** [comment]
Can we sort these tags? 
![image](https://user-images.githubusercontent.com/94069368/197399183-e9a4728d-6682-4546-b2a2-ea04f9fe9b12.png)
